// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAerNPKQ1M6SKQMzFeUKqEFsIu_vESWswo',
    appId: '1:762799195995:web:1fb974f1a23cab4f447c7e',
    messagingSenderId: '762799195995',
    projectId: 'aura-fashion-store',
    authDomain: 'aura-fashion-store.firebaseapp.com',
    storageBucket: 'aura-fashion-store.firebasestorage.app',
    measurementId: 'G-G48029DCFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL6gPN-IItu8iEL0IZdUwrG1g3xTZj64E',
    appId: '1:762799195995:android:2df9e491dc5677ec447c7e',
    messagingSenderId: '762799195995',
    projectId: 'aura-fashion-store',
    storageBucket: 'aura-fashion-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA76mzOrEfGp-IrMvHS613hxxdFlU9mXDA',
    appId: '1:762799195995:ios:80ede7480724333f447c7e',
    messagingSenderId: '762799195995',
    projectId: 'aura-fashion-store',
    storageBucket: 'aura-fashion-store.firebasestorage.app',
    iosBundleId: 'com.aura.auraFashion',
  );
}
